from PySide import QtCore, QtGui

class Ui_Level(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1615, 710)
        MainWindow.setStyleSheet("background-color: rgb(63, 63, 63); color: #ffffff;")
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.estTable = QtGui.QTableWidget(self.centralwidget)
        self.estTable.setGeometry(QtCore.QRect(20, 50, 1271, 281))
        self.estTable.setStyleSheet("background-color: #ffffff; color: #666;")
        self.estTable.setAlternatingRowColors(True)
        self.estTable.setGridStyle(QtCore.Qt.DashLine)
        self.estTable.horizontalHeader().setCascadingSectionResizes(False)
        self.estTable.horizontalHeader().setDefaultSectionSize(40)
        self.estTable.setObjectName("estTable")
        self.estTable.setColumnCount(0)
        self.estTable.setRowCount(0)
        self.lstTable = QtGui.QTableWidget(self.centralwidget)
        self.lstTable.setGeometry(QtCore.QRect(20, 400, 1271, 281))
        self.lstTable.setStyleSheet("background-color: #ffffff; color: #666;")
        self.lstTable.setAlternatingRowColors(True)
        self.lstTable.setGridStyle(QtCore.Qt.DashLine)
        self.lstTable.horizontalHeader().setCascadingSectionResizes(False)
        self.lstTable.horizontalHeader().setDefaultSectionSize(40)
        self.lstTable.setObjectName("lstTable")
        self.lstTable.setColumnCount(0)
        self.lstTable.setRowCount(0)
        self.lstLabel = QtGui.QLabel(self.centralwidget)
        self.lstLabel.setGeometry(QtCore.QRect(20, 20, 321, 17))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        font.setPointSize(14)
        font.setItalic(False)
        self.lstLabel.setFont(font)
        self.lstLabel.setObjectName("lstLabel")
        self.estLabel = QtGui.QLabel(self.centralwidget)
        self.estLabel.setGeometry(QtCore.QRect(20, 370, 331, 17))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        font.setPointSize(14)
        font.setWeight(50)
        font.setBold(False)
        self.estLabel.setFont(font)
        self.estLabel.setObjectName("estLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1615, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.lstLabel.setText(QtGui.QApplication.translate("MainWindow", "RESOURCE LOADING FOR THE EST", None, QtGui.QApplication.UnicodeUTF8))
        self.estLabel.setText(QtGui.QApplication.translate("MainWindow", "RESOURCE LOADING FOR THE LST", None, QtGui.QApplication.UnicodeUTF8))
